language: cpp


jobs:
  include:
    - os: linux
      compiler: g++
      dist: bionic
      sudo: required
    - os: osx
      compiler: clang
      sudo: required 



install: 
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install boost-test
    - ./vcpkg install boost-format
    - ./vcpkg install boost-filesystem
    - ./vcpkg install cimg
    - ./vcpkg install libpng 
    - ./vcpkg install libplist
    - ./vcpkg install libjpeg-turbo
    - ./vcpkg install pybind11
    - ./vcpkg install utfcpp
    - cd ../

script:
    - mkdir ./build
    - cd ./build 
    - pyenv global system 3.7
    - cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ../ 
    - cmake --build ./
    - ctest