language: cpp
sudo: required
dist: bionic
compiler:
    - clang
os:
    - linux
install: 
    - git clone https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh
    - ./vcpkg install boost

script:
    - mkdir ./build
    - cd ./build 
    - cmake -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" ../ 
    - make